#!/usr/bin/env bash

readonly UNPRIVILEGED_USER="podman"
export UNPRIVILEGED_USER

readonly ROOT_SSH_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFm2gQUyfcuGpUi8l/0F8ncyvAg5OaCxEVqrh30of5mU"
export ROOT_SSH_KEY

readonly UNPRIVILEGED_SSH_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFm2gQUyfcuGpUi8l/0F8ncyvAg5OaCxEVqrh30of5mU"
export UNPRIVILEGED_SSH_KEY
